---

- name: Keep packages up to date
  package:
    name: "{{ item }}"
    update_cache: true
    state: latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install Postgresql
  package:
    name: "{{ item }}"
    update_cache: true
    state: installed
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2
  tags: packages

- name: Start Postgresql
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create Database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: 'UTF-8'
    lc_collate: 'en_GB.UTF-8'
    lc_ctype: 'en_GB.UTF-8'
    template: 'template0'
    state: present

- name: Ensure Access
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL
    state: present

- name: Limit privileges
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present

- import_tasks: configure.yaml
